### PR TITLE
:+1: update version

### PR DESCRIPTION
**Pull request by takayukioda**
:+1: small update for PHP test
:recycle: update link in readme
:bug: fix myQuote; set cwd if it didn't passed
:+1: add newline at the end of test

### CODE REVIEW

**Comment by takayukioda** [comment]
@shunjikonishi please review me. I'll work on `npm publish` after this merge

**Comment by shunjikonishi** [comment]
@takayukioda 
What is `small update for PHP test`? 
This one?

https://github.com/code-check/codecheck/pull/67

**Comment by takayukioda** [comment]
@shunjikonishi yes, that issue.
That fix seems not included in latest codecheck.
I've checked this by `git log 0.6.0..release/0.6.1`

**Comment by shunjikonishi** [comment]
LGTM

**Pull request merged**
