### PR TITLE
:recycle: Refactor/myquote

### PR DESCRIPTION
**Pull request by takayukioda**
:recycle: use class syntax to clear the view.
:recycle: add yarn.lock file so we can lock the dependencies
:bug: set default value for cwd if it was empty

### CODE REVIEW

**Comment by takayukioda** [comment]
@shunjikonishi please review me

**Comment by shunjikonishi** [comment]
@takayukioda fix me

**Comment by takayukioda** [comment]
I thought flatten the dependencies and generate lockfile is the biggest benefit using yarn, so that developers don't have to worry about "your code doesn't run in my environment because installed package version is different".
I will introduce yarn in different PR as you suggest 👍

**Comment by takayukioda** [comment]
@shunjikonishi please review me

**Comment by shunjikonishi** [comment]
LGTM

**Pull request merged**
